# Generated by Django 5.0.2 on 2024-02-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
