# Generated by Django 5.0.2 on 2024-03-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postcomment_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='body',
            field=models.TextField(verbose_name=': متن مورد نظر'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='email',
            field=models.EmailField(max_length=254, verbose_name=': ایمیل'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='name',
            field=models.CharField(max_length=80, verbose_name=': نام شما'),
        ),
    ]
