# Generated by Django 5.0.2 on 2024-04-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hello', models.CharField(max_length=100)),
                ('who_am_i', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('cv_button', models.CharField(max_length=50)),
                ('cv_files', models.FileField(upload_to='cv/')),
                ('contact_me_button', models.CharField(max_length=50)),
            ],
        ),
    ]
