# Generated by Django 5.0.2 on 2024-04-08 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_homebanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homebanner',
            options={'verbose_name': 'greeting'},
        ),
        migrations.RenameField(
            model_name='homebanner',
            old_name='cv_files',
            new_name='cv_file',
        ),
    ]
