# Generated by Django 5.0.2 on 2024-04-09 13:55

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_one',
            field=models.ImageField(default='post-img1.jpg', upload_to='post_image/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_two',
            field=models.ImageField(default='post-img2.jpg', upload_to='post_image/'),
        ),
        migrations.AddField(
            model_name='post',
            name='quotes',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
