# Generated by Django 5.0.2 on 2024-04-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_image_one_post_image_two_post_quotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_one',
            field=models.ImageField(default='', upload_to='post_image/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_two',
            field=models.ImageField(default='', upload_to='post_image/'),
        ),
    ]
